### ISSUE TITLE
History relationship link gives incorrect URL

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/jamdb#3]
As discussed with @chrisseto :

The `relationships` field of a document JSONAPI response contains an incorrect and broken link to history. History links should use the full namespaced ID (`experimenter.experiments.test`) rather than the partial ID (`test`).

The link in this field is generated by Jam. In practice, this causes relationships to history to fail when queried directly from an object. 

This can be hacked around in an ember serializer for now.

Sample payload:

```
{...
"relationships": 
  {"history": 
    {"links": 
      {"self": "http://localhost:1212/v2/documents/test/history",
       "related": "http://localhost:1212/v2/documents/test/history"}}}, 
...
}
```

**Comment by chrisseto** [comment]
https://github.com/CenterForOpenScience/jamdb/commit/b4bf41400782c349e611051f1dc297229f99919f
